name: Release
on:
  push:
    branches: [ master ]

jobs:
  release:
    name: NPM
    uses: cnpm/github-actions/.github/workflows/npm-release.yml@master
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    permissions:
      contents: write
      id-token: write
      deployments: write
      issues: write
      pull-requests: write
